const productos = [
    // {
    //     id: 1,
    //     title: 'MacBook Pro 13"',
    //     price: "1199",
    //     pictureUrl: 'https://www.macstation.com.ar/img/productos/small/2211-2212-2134-8.jpg',
    //     pictureUrl2: 'https://outtec.com.ar/wp-content/uploads/2021/08/M1.jpg',
    //     pictureUrl3: 'https://images.fravega.com/f300/bd5ba75838663e3fbc72a268d4f3b1cb.jpg.webp',
    //     option1: 'Space Gray',
    //     option2: 'Silver',
    //     option3: 'Gold',
    //     descripcion1: 'Pantalla Retina de 13.3 pulgadas',
    //     descripcion2: 'Chip M2 de Apple',
    //     descripcion3: 'GPU de 10 núcleos',
    //     descripcion4: 'Touch Bar y Touch ID',
    //     stock: '8',
    //     idCategoria: 'Mac',
        
       
    // },
    // {
    //     id: 2,
    //     title: 'MacBook Air',
    //     price: "999",
    //     pictureUrl: 'https://www.ventasrosario.com.ar/wp-content/uploads/2021/01/Apple-MacBook-Air-2020-tecnolocura-portada.jpg',
    //     pictureUrl2: 'https://cdn-ipoint.waugi.com.ar/20596-medium_default/macbook-air-13-m1-2020-8-core-cpu-256-gb-space-gray.jpg',
    //     pictureUrl3: 'https://www.apple.com/newsroom/images/product/mac/standard/Apple_new-macbookair-gold-bigsur-screen_11102020_big_carousel.jpg.large.jpg',
    //     option1: 'Space Gray',
    //     option2: 'Silver',
    //     option3: 'Gold',
    //     descripcion1: 'Pantalla Retina de 16.2 pulgadas',
    //     descripcion2: 'chip M1 Apple',
    //     descripcion3: 'GPU de 7 núcleos',
    //     descripcion4: 'Touch ID',
    //     stock: '6',
    //     idCategoria: 'Mac',
            
    // },
    // {
    //     id: 3,
    //     title: 'MacBook Pro 16"',
    //     price: "1499",
    //     pictureUrl: 'https://www.apple.com/v/macbook-pro-14-and-16/b/images/overview/hero/hero_intro_endframe__e6khcva4hkeq_large.jpg',
    //     pictureUrl2: 'https://bestfixing.com/wp-content/uploads/2019/01/mbp16touch-silver-select-201911.jpeg',
    //     pictureUrl3: 'https://http2.mlstatic.com/D_NQ_NP_946410-MLA48352501573_112021-O.webp',
    //     option1: 'Space Gray',
    //     option2: 'Silver',
    //     option3: 'Gold',
    //     descripcion1: 'Pantalla Liquid Retina de 16.2 pulgadas',
    //     descripcion2: 'chip M1 Max de Apple',
    //     descripcion3: 'GPU de 32 núcleos',
    //     descripcion4: 'Touch ID',
    //     stock: '5',
    //     idCategoria: 'Mac',
  
    // },
    // {
    //     id: 4,
    //     title: 'iMac"',
    //     price: "1299",
    //     pictureUrl: 'https://www.muycomputer.com/wp-content/uploads/2021/04/iMac-2021-1000x600.jpg',
    //     pictureUrl2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC2a7J9QozkzGZZ7fJg7P0RR-w9witA5sOP1OaECObOYtAY9Zsek_eu0bAQdUiqylQIfw&usqp=CAU',
    //     pictureUrl3: 'https://p.turbosquid.com/ts-thumb/Lk/v4hGxK/y2/appleimac2021silver3dsmodel001/jpg/1626886332/600x600/fit_q87/95e7ad64ccc6699fe16e155aa15f3da7a9091761/appleimac2021silver3dsmodel001.jpg',
    //     option1: 'Blue',
    //     option2: 'Green',
    //     option3: 'Silver',
    //     descripcion1: 'Pantalla  Retina 4.5K de 24 pulgadas',
    //     descripcion2: 'Hasta 2 TB de almacenamiento',
    //     descripcion3: 'Magic Keyboard con touch ID',
    //     descripcion4: 'Camara FaceTime HD de 1080p con ISP',
    //     stock: '9',
    //     idCategoria: 'Mac',
    // },
    // {
    //     id: 5,
    //     title: 'iPad Pro',
    //     price: "799",
    //     pictureUrl: 'https://www.macstation.com.ar/img/productos/2699-1.jpg',
    //     pictureUrl2: 'https://tse1.mm.bing.net/th?id=OIP.oggMbHbjLlfy-iJSAFb-eQHaEj&pid=Api&P=0&w=282&h=173',
    //     pictureUrl3: 'https://www.macstation.com.ar/img/productos/2430-2.jpg',
    //     option1: '128GB',
    //     option2: ' 256GB',
    //     option3: '512GB',
    //     descripcion1: 'Pantalla Liquid Retina XDR 12.9"',
    //     descripcion2: 'FaceID ',
    //     descripcion3: 'Chip M1 de Apple',
    //     descripcion4: 'Compatible con Apple Pencil',
    //     stock: '12',
    //     idCategoria: 'iPad',
    // },
    // {
    //     id: 6,
    //     title: 'iPad Air',
    //     price: "599",
    //     pictureUrl: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/ipad-air-select-202203?wid=3530&hei=4000&fmt=jpeg&qlt=90&.v=1645665079887',
    //     pictureUrl2: 'https://m.media-amazon.com/images/I/61XZQXFQeVL._AC_SL1500_.jpg',
    //     pictureUrl3: 'https://www.k-tuin.com/media/wysiwyg/blog/2022/Marzo/ipad-air-4-vs-ipad-air-5_1.jpg',
    //     option1: '64GB',
    //     option2: ' 128GB',
    //     option3: '256GB',
    //     descripcion1: 'Pantalla Liquid Retina 10.9"',
    //     descripcion2: 'FaceID ',
    //     descripcion3: 'Chip M1 de Apple',
    //     descripcion4: 'Compatible con Apple Pencil',
    //     stock: '11',
    //     idCategoria: 'iPad',
    // },
    // {
    //     id: 7,
    //     title: 'iPad 8th Gen',
    //     price: "499",
    //     pictureUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_kA7LIG7WCqUKJWqgJtGIADYly1DF96NPmhObl_9G5don1MoCBruviGohqxZbqT4mZvs&usqp=CAU',
    //     pictureUrl2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBw4XwF77LJtT9c5qiwVVot40f9hEpvznbLnAnKtjMtTPVMvusgXWPCQcvhXF-WGzoQ1Q&usqp=CAU',
    //     pictureUrl3: 'http://www.perusmart.com/wp-content/uploads/iPad-8th-precio-peru.jpg',
    //     option1: '64GB',
    //     option2: ' 128GB',
    //     option3: '256GB',
    //     descripcion1: 'Pantalla Retina 10.2"',
    //     descripcion2: 'Touch ID',
    //     descripcion3: 'Chip A13 Bionic de Apple',
    //     descripcion4: 'Compatible con Apple Pencil',
    //     stock: '16',
    //     idCategoria: 'iPad',
    // },
    // {
    //     id: 8,
    //     title: 'iPhone SE',
    //     price: "429",
    //     pictureUrl: 'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-se-family-select-202203_GEO_EMEA?wid=940&hei=1112&fmt=jpeg&qlt=90&.v=1646070492835',
    //     pictureUrl2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXHaWNZuOxcAggHwsVhoiR5pBlrPg-GXyQQxagz1uzB4bFqhoTLl6b3yovR8c9Dpvnwpg&usqp=CAU',
    //     pictureUrl3: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa1JBFSZRuLDYNMDrL_CQcRBXAT0rjZTuJgDPsFrCNBbjtyFPYGO9gnp3oFvx7mebu8aA&usqp=CAU',
    //     option1: '64GB',
    //     option2: ' 128GB',
    //     option3: '256GB',
    //     descripcion1: 'Pantalla Retina 4.7"',
    //     descripcion2: 'Touch ID',
    //     descripcion3: 'Chip A15 Bionic de Apple',
    //     descripcion4: 'Cámara gran angular de 12 MP',
    //     stock: '21',
    //     idCategoria: 'iPhone',
    // },
    // {
    //     id: 9,
    //     title: 'iPhone 12',
    //     price: "599",
    //     pictureUrl: 'https://cf.shopee.com.ar/file/9a792333affec7b914286a8d34c5648f',
    //     pictureUrl2: 'https://www.muycomputer.com/wp-content/uploads/2020/10/iPhone-12-est%C3%A1ndar.jpg',
    //     pictureUrl3: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpmRke7YTzW7o01AAkeXQT0xO3M-MK9JFhVjbkRvCE8GOG1UByv9ZlwPUc0uWckgQsICY&usqp=CAU',
    //     option1: '64GB',
    //     option2: ' 128GB',
    //     option3: '256GB',
    //     descripcion1: 'Pantalla Super Retina OLED 6.1"',
    //     descripcion2: 'Face ID',
    //     descripcion3: 'Chip A14 Bionic de Apple',
    //     descripcion4: 'Sistema de dos cámaras de 12 MP: ultra gran angular y gran angular',
    //     stock: '11',
    //     idCategoria: 'iPhone',
    // },
    // {
    //     id: 10,
    //     title: 'iPhone 13',
    //     price: "699",
    //     pictureUrl: 'https://resizer.glanacion.com/resizer/eGzjmDdcbqeXgIJ3KS_THb7rx2c=/768x0/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/N32MA5DHRFGBPLDOTK664H2KCU.jpg',
    //     pictureUrl2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpmjmocaYwLshhShTCnehNnecBkkpY1uV0sg_LWGXv3AS7j7qROpO84x2spRO5fhLWCQI&usqp=CAU',
    //     pictureUrl3: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXc7kItrLzScgMCbfIoHRfKYwWVqzlcrRrBbqtRpd9eFQBEijChnZfPxwLC1wCfpa6x8Y&usqp=CAU',
    //     option1: '128GB',
    //     option2: ' 256GB',
    //     option3: '512GB',
    //     descripcion1: 'Pantalla Super Retina OLED 6.1"',
    //     descripcion2: 'Face ID',
    //     descripcion3: 'Chip A15 Bionic de Apple',
    //     descripcion4: 'Sistema de dos cámaras de 12 MP: ultra gran angular y gran angular',
    //     stock: '16',
    //     idCategoria: 'iPhone',
    // },
    // {
    //     id: 11,
    //     title: 'iPhone 13 Pro',
    //     price: "999",
    //     pictureUrl: 'https://internacionalmobile.store/wp-content/uploads/2021/09/iphone13pro.jpg',
    //     pictureUrl2: 'https://cdn-ipoint.waugi.com.ar/22569-large_default/iphone-13-pro-256gb-silver.jpg',
    //     pictureUrl3: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMFypOxvsFjoosz2v4rmpa_iaiYMYLwrwQXGwWkHUNAXPRu1UsaFD_0U968IjppohhF1E&usqp=CAU',
    //     option1: '128GB',
    //     option2: ' 256GB',
    //     option3: '512GB',
    //     descripcion1: 'Pantalla Super Retina XDR con ProMotion 6.1"',
    //     descripcion2: 'Face ID',
    //     descripcion3: 'Chip A15 Bionic de Apple',
    //     descripcion4: 'Sistema de cámaras Pro de 12 MP: teleobjetivo, gran angular y ultra gran angular',
    //     stock: '15',
    //     idCategoria: 'iPhone',
    // },
    // {
    //     id: 12,
    //     title: 'Apple Watch SE',
    //     price: "299",
    //     pictureUrl: 'https://www.venex.com.ar/products_images/1632760380_apple-watch-se-202107.jpg',
    //     pictureUrl2: 'https://http2.mlstatic.com/D_NQ_NP_752671-MLA47794960094_102021-V.jpg',
    //     pictureUrl3: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7Qli4WOCx463h3yTB4iEAOOM7bO7w0xRycCq5DwqVGJvdsZ40ddkiYUOv87tWdF_IbZ0&usqp=CAU',
    //     option1: '38mm',
    //     option2: ' 42mm',
    //     option3: ' 44mm',
    //     descripcion1: 'Pantalla 30% más grande que la del Series 3',
    //     descripcion2: 'Notificaciones de frecuencia cardiaca alta y baja',
    //     descripcion3: 'Emergencia SOS',
    //     descripcion4: 'Conexión celular disponible',
    //     stock: '19',
    //     idCategoria: 'Watch',
    // },
    // {
    //     id: 13,
    //     title: 'Apple Watch Series 3',
    //     price: "399",
    //     pictureUrl: 'https://www.apple.com/newsroom/images/product/watch/standard/applewatch_series_3_two_loop_full.jpg.og.jpg?202205262042',
    //     pictureUrl2: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV3NDhKp6snY5Y3ngeLOXKKSk11fXwKBmQX8lmm4yraI0ja3HAn0ww_O61y64obay8wik&usqp=CAU',
    //     pictureUrl3: 'https://evoluciontechnology.com/wp-content/uploads/2021/06/apple-watch-s3-og-202003.jpg',
    //     option1: '40mm',
    //     option2: '42mm',
    //     option3: '44mm',
    //     descripcion1: 'Diseñado para nadar',
    //     descripcion2: 'Pantalla Retina',
    //     descripcion3: 'Notificaciones de frecuencia cardiaca alta y baja',
    //     descripcion4: 'Emergencia SOS',
    //     stock: '10',
    //     idCategoria: 'Watch',
    // },
    // {
    //     id: 14,
    //     title: 'Apple Wactch Series 7',
    //     price: "499",
    //     pictureUrl: 'https://www.apple.com/newsroom/images/product/watch/standard/Apple_watch-series7-availability_hero_10052021_big.jpg.slideshow-xlarge_2x.jpg',
    //     pictureUrl2: 'https://www.apple.com/newsroom/images/product/watch/standard/Apple_watch-series7-availability_stainless-steel_10052021_big_carousel.jpg.large.jpg',
    //     pictureUrl3: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSoGAeft9w2Ah5tSYMI34G22gabNVksJcfrocR7ADetCaLLB3I7qyESO1s_V55R768D_QI&usqp=CAU',
    //     option1: '40mm',
    //     option2: '42mm',
    //     option3: '45mm',
    //     descripcion1: 'Certificación IP6X de resistencia',
    //     descripcion2: 'Pantalla 20% más grande que la del Apple Watch SE',
    //     descripcion3: 'Notificaciones de frecuencia cardiaca alta y baja',
    //     descripcion4: 'Emergencia SOS',
    //     stock: '16',
    //     idCategoria: 'Watch',
    // },
    // {
    //     id: 15,
    //     title: 'AirPods 2da Gen',
    //     price: "199",
    //     pictureUrl: 'https://www.apple.com/v/airpods-2nd-generation/e/images/meta/og__bz8g5g9sbyoi_overview.png?202205060638',
    //     pictureUrl2: 'https://lamanzanamordida.net/app/uploads-lamanzanamordida.net/2019/03/maxresdefault-3.jpg',
    //     pictureUrl3: 'https://d2r9epyceweg5n.cloudfront.net/stores/001/778/595/products/mv7n2ama_31-c197f955d59ffd34b216329239489151-1024-1024.jpg',
    //     option1: '  ',
    //     option2: 'White',
    //     option3: '  ',
    //     descripcion1: 'Carga mediante Lightning',
    //     descripcion2: 'Hasta 5 horas de audio',
    //     descripcion3: 'Resistencia al sudor ',
    //     descripcion4: 'Detección automática de dispositivo',
    //     stock: '13',
    //     idCategoria: 'AirPods',
    // },
    // {
    //     id: 16,
    //     title: 'AirPods Pro',
    //     price: "329",
    //     pictureUrl: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MWP22?wid=2000&hei=2000&fmt=jpeg&qlt=95&.v=1591634795000',
    //     pictureUrl2: 'https://www.sbsmobile.com/aus/199530-thickbox_default/funda-de-silicona-para-apple-airpods-pro.jpg',
    //     pictureUrl3: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MWP22_AV1?wid=1144&hei=1144&fmt=jpeg&qlt=90&.v=1591634652000',
    //     option1: '-',
    //     option2: 'White',
    //     option3: '-',
    //     descripcion1: 'Carga inalambrica y mediante Lightning',
    //     descripcion2: 'Hasta 6 horas de audio',
    //     descripcion3: 'Resistencia al agua y sudor',
    //     descripcion4: 'Audio espacial y cancelacion activa de ruido',
    //     stock: '23',
    //     idCategoria: 'AirPods',
    // },
//     {
//         id: 17,
//         title: 'AirPods Max',
//         price: "599",
//         pictureUrl: 'https://cloudfront-us-east-1.images.arcpublishing.com/infobae/P6DXXC4C6VCHJKWCAELS7EN5SI.webp',
//         pictureUrl2: 'https://cdn.shopify.com/s/files/1/0101/2522/products/airpods-max-select-skyblue-202011_1200x.png?v=1611096138',
//         pictureUrl3: 'https://media.revistagq.com/photos/5fcf829e0725a0bdb22db832/master/pass/apple_airpods-max_pairing_12082020.jpg',
//         option1: 'Space Grey',
//         option2: 'Silver',
//         option3: 'Sky Blue',
//         descripcion1: 'Carga mediante Lightning',
//         descripcion2: 'Hasta 20 horas de audio',
//         descripcion3: 'Resistencia al agua y sudor',
//         descripcion4: 'Audio espacial y cancelacion activa de ruido',
//         stock: '23',
//         idCategoria: 'AirPods',
//     },
]

export default productos;